### ISSUE TITLE
DyLoRA：AttributeError: 'Linear' object has no attribute 'get_dimension'

### ISSUE THREAD

**Issue by YaoLiang-Code** [huawei-noah/KD-NLP#9]
When I run DyLoRA‘s cola task, I get this error.

**Comment by Sun-9923** [comment]
Hello, I also encountered the same problem, how did you solve it?

**Comment by YaoLiang-Code** [comment]
Hi, It's a dependency issue with the package. You can check if the package dependency is correct.




梁尧
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/Efficient-NLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 下午4:43
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/Efficient-NLP] DyLoRA：AttributeError: 'Linear' object has no attribute 'get_dimension' (Issue #9)





 
Hello, I also encountered the same problem, how did you solve it?

**Comment by Sun-9923** [comment]
> Hi, It's a dependency issue with the package. You can check if the package dependency is correct. 梁尧 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "huawei-noah/Efficient-NLP" ***@***.***&gt;; 发送时间:&nbsp;2024年5月14日(星期二) 下午4:43 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [huawei-noah/Efficient-NLP] DyLoRA：AttributeError: 'Linear' object has no attribute 'get_dimension' (Issue #9) Hello, I also encountered the same problem, how did you solve it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

Alright, thank you very much.

**Comment by YaoLiang-Code** [comment]
You're welcome.




梁尧
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/Efficient-NLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 下午4:55
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/Efficient-NLP] DyLoRA：AttributeError: 'Linear' object has no attribute 'get_dimension' (Issue #9)





  
Hi, It's a dependency issue with the package. You can check if the package dependency is correct. 梁尧 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "huawei-noah/Efficient-NLP" @.&gt;; 发送时间:&nbsp;2024年5月14日(星期二) 下午4:43 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [huawei-noah/Efficient-NLP] DyLoRA：AttributeError: 'Linear' object has no attribute 'get_dimension' (Issue #9) Hello, I also encountered the same problem, how did you solve it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
Alright, thank you very much.
